spring.application.name=filemanager
# Enable the H2 console
spring.h2.console.enabled=true
# Set the path for the H2 console
spring.h2.console.path=/h2-console

# Configure the JDBC URL for an in-memory database named 'testdb'
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configure JPA/Hibernate settings (optional but recommended)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
